USE [master]
GO

/****** Object:  Database [RajdeepBankDB]    Script Date: 21-12-2015 22:03:05 ******/
CREATE DATABASE [RajdeepBankDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RajdeepBank', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\RajdeepBank.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RajdeepBank_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\RajdeepBank_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [RajdeepBankDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RajdeepBankDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RajdeepBankDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RajdeepBankDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RajdeepBankDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RajdeepBankDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RajdeepBankDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [RajdeepBankDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RajdeepBankDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RajdeepBankDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RajdeepBankDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RajdeepBankDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RajdeepBankDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RajdeepBankDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RajdeepBankDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RajdeepBankDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RajdeepBankDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RajdeepBankDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RajdeepBankDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RajdeepBankDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RajdeepBankDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RajdeepBankDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RajdeepBankDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RajdeepBankDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RajdeepBankDB] SET RECOVERY FULL 
GO

ALTER DATABASE [RajdeepBankDB] SET  MULTI_USER 
GO

ALTER DATABASE [RajdeepBankDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RajdeepBankDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RajdeepBankDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RajdeepBankDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [RajdeepBankDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RajdeepBankDB] SET  READ_WRITE 
GO


